### PR TITLE
Homepage would be nice

### PR DESCRIPTION
**Pull request by alyxrossetti**

### CODE REVIEW

**Comment by alyxrossetti** [comment]
Closes #96

**Comment by workergnome** [comment]
Two things--

can we re-add the style block?  It manages styles for the per-term and per-concept ids:

screen shot 2018-03-12 at 5 34 12 pm

And do you think it makes sense to use a `v-else` rather than two `v-if` statements in App.vue? https://vuejs.org/v2/guide/conditional.html#v-else

**Comment by workergnome** [comment]
(Open for suggestions for a better place to put reused styles...

**Comment by alyxrossetti** [comment]
Yes to both! Done and done.

**Comment by workergnome** [comment]
OK.  More nits.  

Why are we importing `language` as a prop here?  It doesn't look like it's used anywhere.

**Comment by alyxrossetti** [comment]
Fair point. Removed.

**Pull request merged**
